/* moy.c generated by valac 0.48.6, the Vala compiler
 * generated from moy.vala, do not modify */

/* modules: gio-2.0 posix*/
/* vapidirs: vapi*/
/* sources: main.vala moy.vala*/

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>

#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_MOYENNE (moyenne_get_type ())
#define MOYENNE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOYENNE, Moyenne))
#define MOYENNE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOYENNE, MoyenneClass))
#define IS_MOYENNE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOYENNE))
#define IS_MOYENNE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOYENNE))
#define MOYENNE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOYENNE, MoyenneClass))

typedef struct _Moyenne Moyenne;
typedef struct _MoyenneClass MoyenneClass;
typedef struct _MoyennePrivate MoyennePrivate;
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
typedef struct _ParamSpecMoyenne ParamSpecMoyenne;
#define _moyenne_unref0(var) ((var == NULL) ? NULL : (var = (moyenne_unref (var), NULL)))

struct _Moyenne {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MoyennePrivate * priv;
};

struct _MoyenneClass {
	GTypeClass parent_class;
	void (*finalize) (Moyenne *self);
};

struct _MoyennePrivate {
	gint m_puissance;
	gdouble m_moy;
	guint m_max;
	gint m_foix;
};

struct _ParamSpecMoyenne {
	GParamSpec parent_instance;
};

static gint Moyenne_private_offset;
static gpointer moyenne_parent_class = NULL;
extern gchar* push_swap_emp;

#define GREEN "\033[1;92m"
#define BLUE "\033[1;36m"
#define YELLOW "\033[1;93m"
#define ORANGE "\033[1;91m"
#define RED "\033[1;31m"
#define NONE "\033[0m"
gint* ft_get_random_tab (gint size,
                         gint* result_length1);
static gboolean _vala_int_array_contains (gint * stack,
                                   gint stack_length,
                                   const gint needle);
gchar* ft_tab_to_string (gint* tab,
                         gint tab_length1);
gpointer moyenne_ref (gpointer instance);
void moyenne_unref (gpointer instance);
GParamSpec* param_spec_moyenne (const gchar* name,
                                const gchar* nick,
                                const gchar* blurb,
                                GType object_type,
                                GParamFlags flags);
void value_set_moyenne (GValue* value,
                        gpointer v_object);
void value_take_moyenne (GValue* value,
                         gpointer v_object);
gpointer value_get_moyenne (const GValue* value);
GType moyenne_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Moyenne, moyenne_unref)
Moyenne* moyenne_new (gint puissance,
                      gint foix);
Moyenne* moyenne_construct (GType object_type,
                            gint puissance,
                            gint foix);
gchar* moyenne_get_push_swap_string (Moyenne* self,
                                     const gchar* str_tab);
gchar* moyenne_call_checker (Moyenne* self,
                             const gchar* str,
                             const gchar* str_tab);
guint moyenne_count_line (Moyenne* self,
                          const gchar* tab);
static guint8* _vala_array_dup1 (guint8* self,
                          gint length);
void moyenne_print_func (Moyenne* self,
                         const gchar* out_push,
                         const gchar* out_check,
                         const gchar* tab);
void moyenne_add_moy (Moyenne* self,
                      guint nbr);
void moyenne_change_max (Moyenne* self,
                         guint max);
void moyenne_run (Moyenne* self);
void moyenne_teste (Moyenne* self);
static void moyenne_finalize (Moyenne * obj);
static GType moyenne_get_type_once (void);
void calc_moy (gchar** args,
               gint args_length1);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static gboolean
_vala_int_array_contains (gint * stack,
                          gint stack_length,
                          const gint needle)
{
	gint i;
	for (i = 0; i < stack_length; i++) {
		if (needle == stack[i]) {
			return TRUE;
		}
	}
	return FALSE;
}

gint*
ft_get_random_tab (gint size,
                   gint* result_length1)
{
	gint* tab = NULL;
	gint* _tmp0_;
	gint tab_length1;
	gint _tab_size_;
	gint n = 0;
	gint* _tmp6_;
	gint _tmp6__length1;
	gint* result = NULL;
	_tmp0_ = g_new0 (gint, size);
	tab = _tmp0_;
	tab_length1 = size;
	_tab_size_ = tab_length1;
	n = 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint* _tmp3_;
				gint _tmp3__length1;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				if (!(i != size)) {
					break;
				}
				n = (gint) g_random_int_range ((gint32) G_MININT, (gint32) G_MAXINT);
				_tmp3_ = tab;
				_tmp3__length1 = tab_length1;
				if (_vala_int_array_contains (_tmp3_, _tmp3__length1, n)) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ - 1;
				} else {
					gint* _tmp5_;
					gint _tmp5__length1;
					_tmp5_ = tab;
					_tmp5__length1 = tab_length1;
					_tmp5_[i] = n;
				}
			}
		}
	}
	_tmp6_ = tab;
	_tmp6__length1 = tab_length1;
	if (result_length1) {
		*result_length1 = _tmp6__length1;
	}
	result = _tmp6_;
	return result;
}

gchar*
ft_tab_to_string (gint* tab,
                  gint tab_length1)
{
	gchar* str = NULL;
	gchar* _tmp0_;
	gchar* result = NULL;
	_tmp0_ = g_strdup ("");
	str = _tmp0_;
	{
		gint* i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = tab;
		i_collection_length1 = tab_length1;
		for (i_it = 0; i_it < i_collection_length1; i_it = i_it + 1) {
			gint i = 0;
			i = i_collection[i_it];
			{
				const gchar* _tmp1_;
				gchar* _tmp2_;
				gchar* _tmp3_;
				gchar* _tmp4_;
				gchar* _tmp5_;
				gchar* _tmp6_;
				_tmp1_ = str;
				_tmp2_ = g_strdup_printf ("%i", i);
				_tmp3_ = _tmp2_;
				_tmp4_ = g_strconcat (_tmp3_, " ", NULL);
				_tmp5_ = _tmp4_;
				_tmp6_ = g_strconcat (_tmp1_, _tmp5_, NULL);
				_g_free0 (str);
				str = _tmp6_;
				_g_free0 (_tmp5_);
				_g_free0 (_tmp3_);
			}
		}
	}
	result = str;
	return result;
}

static inline gpointer
moyenne_get_instance_private (Moyenne* self)
{
	return G_STRUCT_MEMBER_P (self, Moyenne_private_offset);
}

Moyenne*
moyenne_construct (GType object_type,
                   gint puissance,
                   gint foix)
{
	Moyenne* self = NULL;
	self = (Moyenne*) g_type_create_instance (object_type);
	self->priv->m_puissance = puissance;
	self->priv->m_moy = 0.0;
	self->priv->m_max = (guint) 0;
	self->priv->m_foix = foix;
	return self;
}

Moyenne*
moyenne_new (gint puissance,
             gint foix)
{
	return moyenne_construct (TYPE_MOYENNE, puissance, foix);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

gchar*
moyenne_get_push_swap_string (Moyenne* self,
                              const gchar* str_tab)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gint fds[2] = {0};
	pid_t pid = 0;
	gint _tmp10_;
	FILE* stream = NULL;
	gint _tmp11_;
	FILE* _tmp12_;
	gchar buf[400] = {0};
	gint _tmp17_;
	gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (str_tab != NULL, NULL);
	_tmp0_ = g_strdup ("");
	_result_ = _tmp0_;
	pipe (fds);
	pid = fork ();
	if (pid == ((pid_t) 0)) {
		gint _tmp1_;
		gchar** av = NULL;
		gchar* _tmp2_;
		gchar* _tmp3_;
		gchar** _tmp4_;
		gint av_length1;
		gint _av_size_;
		gint _tmp5_;
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		gchar** _tmp8_;
		gint _tmp8__length1;
		gint _tmp9_;
		_tmp1_ = fds[0];
		close (_tmp1_);
		_tmp2_ = g_strdup ("push_swap");
		_tmp3_ = g_strdup (str_tab);
		_tmp4_ = g_new0 (gchar*, 2 + 1);
		_tmp4_[0] = _tmp2_;
		_tmp4_[1] = _tmp3_;
		av = _tmp4_;
		av_length1 = 2;
		_av_size_ = av_length1;
		_tmp5_ = fds[1];
		dup2 (_tmp5_, 1);
		_tmp6_ = push_swap_emp;
		_tmp7_ = string_to_string (_tmp6_);
		_tmp8_ = av;
		_tmp8__length1 = av_length1;
		execv (_tmp7_, _tmp8_);
		_tmp9_ = fds[1];
		close (_tmp9_);
		exit (0);
		av = (_vala_array_free (av, av_length1, (GDestroyNotify) g_free), NULL);
	}
	_tmp10_ = fds[1];
	close (_tmp10_);
	waitpid (pid, NULL, 0);
	_tmp11_ = fds[0];
	_tmp12_ = fdopen (_tmp11_, "r");
	stream = _tmp12_;
	while (TRUE) {
		FILE* _tmp13_;
		const gchar* _tmp14_;
		const gchar* _tmp15_;
		gchar* _tmp16_;
		_tmp13_ = stream;
		_tmp14_ = fgets (buf, (gint) 400, _tmp13_);
		if (!(_tmp14_ != NULL)) {
			break;
		}
		_tmp15_ = _result_;
		_tmp16_ = g_strconcat (_tmp15_, (const gchar*) buf, NULL);
		_g_free0 (_result_);
		_result_ = _tmp16_;
	}
	_tmp17_ = fds[0];
	close (_tmp17_);
	result = _result_;
	_fclose0 (stream);
	return result;
}

gchar*
moyenne_call_checker (Moyenne* self,
                      const gchar* str,
                      const gchar* str_tab)
{
	gint fds_out[2] = {0};
	gchar* _result_ = NULL;
	pid_t pid = 0;
	gint fds[2] = {0};
	gint _tmp3_;
	pid_t pid2 = 0;
	gint _tmp14_;
	gint _tmp15_;
	guint8 buf[10] = {0};
	gint _tmp16_;
	gchar* _tmp17_;
	gint _tmp18_;
	gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (str != NULL, NULL);
	g_return_val_if_fail (str_tab != NULL, NULL);
	pipe (fds_out);
	pid = fork ();
	if (pid == ((pid_t) 0)) {
		gint _tmp0_;
		gint _tmp1_;
		gint _tmp2_;
		_tmp0_ = fds_out[0];
		close (_tmp0_);
		_tmp1_ = fds_out[1];
		dup2 (_tmp1_, 1);
		printf ("%s", str);
		_tmp2_ = fds_out[1];
		close (_tmp2_);
		exit (0);
	}
	waitpid (pid, NULL, 0);
	pipe (fds);
	_tmp3_ = fds_out[1];
	close (_tmp3_);
	pid2 = fork ();
	if (pid2 == ((pid_t) 0)) {
		gint _tmp4_;
		gint _tmp5_;
		gchar** av = NULL;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar** _tmp8_;
		gint av_length1;
		gint _av_size_;
		gint _tmp9_;
		gint _tmp10_;
		gchar** _tmp11_;
		gint _tmp11__length1;
		gint _tmp12_;
		gint _tmp13_;
		_tmp4_ = fds[0];
		close (_tmp4_);
		_tmp5_ = fds_out[1];
		close (_tmp5_);
		_tmp6_ = g_strdup ("checker_linux");
		_tmp7_ = g_strdup (str_tab);
		_tmp8_ = g_new0 (gchar*, 2 + 1);
		_tmp8_[0] = _tmp6_;
		_tmp8_[1] = _tmp7_;
		av = _tmp8_;
		av_length1 = 2;
		_av_size_ = av_length1;
		_tmp9_ = fds_out[0];
		dup2 (_tmp9_, 0);
		_tmp10_ = fds[1];
		dup2 (_tmp10_, 1);
		_tmp11_ = av;
		_tmp11__length1 = av_length1;
		execv ("checker_linux", _tmp11_);
		_tmp12_ = fds_out[0];
		close (_tmp12_);
		_tmp13_ = fds[1];
		close (_tmp13_);
		exit (0);
		av = (_vala_array_free (av, av_length1, (GDestroyNotify) g_free), NULL);
	}
	waitpid (pid2, NULL, 0);
	_tmp14_ = fds_out[1];
	close (_tmp14_);
	_tmp15_ = fds_out[0];
	close (_tmp15_);
	_tmp16_ = fds[0];
	read (_tmp16_, &buf, (gsize) 10);
	_tmp17_ = g_strdup ((const gchar*) buf);
	_g_free0 (_result_);
	_result_ = _tmp17_;
	_tmp18_ = fds[0];
	close (_tmp18_);
	result = _result_;
	return result;
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res;
	_tmp2__length1 = res_length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}

static guint8*
_vala_array_dup1 (guint8* self,
                  gint length)
{
	return g_memdup (self, length * sizeof (guint8));
}

guint
moyenne_count_line (Moyenne* self,
                    const gchar* tab)
{
	guint nbr = 0U;
	guint i = 0U;
	guint8* s = NULL;
	guint8* _tmp0_;
	gint _tmp0__length1;
	gint _tmp1_ = 0;
	guint8* _tmp2_;
	gint _tmp2__length1;
	guint8* _tmp3_;
	gint _tmp3__length1;
	gint s_length1;
	gint _s_size_;
	guint result = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	g_return_val_if_fail (tab != NULL, 0U);
	nbr = (guint) 0;
	i = (guint) 0;
	_tmp0_ = string_get_data (tab, &_tmp1_);
	_tmp0__length1 = _tmp1_;
	_tmp2_ = _tmp0_;
	_tmp2__length1 = _tmp0__length1;
	_tmp3_ = (_tmp2_ != NULL) ? _vala_array_dup1 (_tmp2_, _tmp2__length1) : ((gpointer) _tmp2_);
	_tmp3__length1 = _tmp2__length1;
	s = _tmp3_;
	s_length1 = _tmp3__length1;
	_s_size_ = s_length1;
	while (TRUE) {
		guint8* _tmp4_;
		gint _tmp4__length1;
		guint8 _tmp5_;
		guint8* _tmp6_;
		gint _tmp6__length1;
		guint8 _tmp7_;
		guint _tmp9_;
		_tmp4_ = s;
		_tmp4__length1 = s_length1;
		_tmp5_ = _tmp4_[i];
		if (!(_tmp5_ != ((guint8) '\0'))) {
			break;
		}
		_tmp6_ = s;
		_tmp6__length1 = s_length1;
		_tmp7_ = _tmp6_[i];
		if (_tmp7_ == ((guint8) '\n')) {
			guint _tmp8_;
			_tmp8_ = nbr;
			nbr = _tmp8_ + 1;
		}
		_tmp9_ = i;
		i = _tmp9_ + 1;
	}
	result = nbr;
	s = (g_free (s), NULL);
	return result;
}

void
moyenne_print_func (Moyenne* self,
                    const gchar* out_push,
                    const gchar* out_check,
                    const gchar* tab)
{
	guint nbr = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (tab != NULL);
	nbr = moyenne_count_line (self, out_push);
	moyenne_add_moy (self, nbr);
	moyenne_change_max (self, nbr);
	if (g_strcmp0 (out_check, "OK\n") == 0) {
		printf ("\033[1;32m[OK] \033[0m");
	} else {
		const gchar* _tmp0_;
		gchar* _tmp1_;
		gchar* _tmp2_;
		_tmp0_ = string_to_string (tab);
		_tmp1_ = g_strconcat ("\033[1;31m[KO] {", _tmp0_, "}\033[0m", NULL);
		_tmp2_ = _tmp1_;
		printf ("%s", _tmp2_);
		_g_free0 (_tmp2_);
	}
	if (self->priv->m_puissance <= 100) {
		if (nbr < ((guint) 700)) {
			const gchar* _tmp3_;
			gchar* _tmp4_;
			gchar* _tmp5_;
			const gchar* _tmp6_;
			gchar* _tmp7_;
			gchar* _tmp8_;
			_tmp3_ = string_to_string (GREEN);
			_tmp4_ = g_strdup_printf ("%u", nbr);
			_tmp5_ = _tmp4_;
			_tmp6_ = string_to_string (NONE);
			_tmp7_ = g_strconcat ("Nombre de coups : ", _tmp3_, _tmp5_, _tmp6_, "\n", NULL);
			_tmp8_ = _tmp7_;
			printf ("%s", _tmp8_);
			_g_free0 (_tmp8_);
			_g_free0 (_tmp5_);
		} else {
			if (nbr < ((guint) 900)) {
				const gchar* _tmp9_;
				gchar* _tmp10_;
				gchar* _tmp11_;
				const gchar* _tmp12_;
				gchar* _tmp13_;
				gchar* _tmp14_;
				_tmp9_ = string_to_string (BLUE);
				_tmp10_ = g_strdup_printf ("%u", nbr);
				_tmp11_ = _tmp10_;
				_tmp12_ = string_to_string (NONE);
				_tmp13_ = g_strconcat ("Nombre de coups : ", _tmp9_, _tmp11_, _tmp12_, "\n", NULL);
				_tmp14_ = _tmp13_;
				printf ("%s", _tmp14_);
				_g_free0 (_tmp14_);
				_g_free0 (_tmp11_);
			} else {
				if (nbr < ((guint) 1100)) {
					const gchar* _tmp15_;
					gchar* _tmp16_;
					gchar* _tmp17_;
					const gchar* _tmp18_;
					gchar* _tmp19_;
					gchar* _tmp20_;
					_tmp15_ = string_to_string (YELLOW);
					_tmp16_ = g_strdup_printf ("%u", nbr);
					_tmp17_ = _tmp16_;
					_tmp18_ = string_to_string (NONE);
					_tmp19_ = g_strconcat ("Nombre de coups : ", _tmp15_, _tmp17_, _tmp18_, "\n", NULL);
					_tmp20_ = _tmp19_;
					printf ("%s", _tmp20_);
					_g_free0 (_tmp20_);
					_g_free0 (_tmp17_);
				} else {
					if (nbr < ((guint) 1500)) {
						const gchar* _tmp21_;
						gchar* _tmp22_;
						gchar* _tmp23_;
						const gchar* _tmp24_;
						gchar* _tmp25_;
						gchar* _tmp26_;
						_tmp21_ = string_to_string (ORANGE);
						_tmp22_ = g_strdup_printf ("%u", nbr);
						_tmp23_ = _tmp22_;
						_tmp24_ = string_to_string (NONE);
						_tmp25_ = g_strconcat ("Nombre de coups : ", _tmp21_, _tmp23_, _tmp24_, "\n", NULL);
						_tmp26_ = _tmp25_;
						printf ("%s", _tmp26_);
						_g_free0 (_tmp26_);
						_g_free0 (_tmp23_);
					} else {
						const gchar* _tmp27_;
						gchar* _tmp28_;
						gchar* _tmp29_;
						const gchar* _tmp30_;
						gchar* _tmp31_;
						gchar* _tmp32_;
						_tmp27_ = string_to_string (RED);
						_tmp28_ = g_strdup_printf ("%u", nbr);
						_tmp29_ = _tmp28_;
						_tmp30_ = string_to_string (NONE);
						_tmp31_ = g_strconcat ("Nombre de coups : ", _tmp27_, _tmp29_, _tmp30_, "\n", NULL);
						_tmp32_ = _tmp31_;
						printf ("%s", _tmp32_);
						_g_free0 (_tmp32_);
						_g_free0 (_tmp29_);
					}
				}
			}
		}
	} else {
		if (self->priv->m_puissance <= 500) {
			if (nbr < ((guint) 5500)) {
				const gchar* _tmp33_;
				gchar* _tmp34_;
				gchar* _tmp35_;
				const gchar* _tmp36_;
				gchar* _tmp37_;
				gchar* _tmp38_;
				_tmp33_ = string_to_string (GREEN);
				_tmp34_ = g_strdup_printf ("%u", nbr);
				_tmp35_ = _tmp34_;
				_tmp36_ = string_to_string (NONE);
				_tmp37_ = g_strconcat ("Nombre de coups : ", _tmp33_, _tmp35_, _tmp36_, "\n", NULL);
				_tmp38_ = _tmp37_;
				printf ("%s", _tmp38_);
				_g_free0 (_tmp38_);
				_g_free0 (_tmp35_);
			} else {
				if (nbr < ((guint) 7000)) {
					const gchar* _tmp39_;
					gchar* _tmp40_;
					gchar* _tmp41_;
					const gchar* _tmp42_;
					gchar* _tmp43_;
					gchar* _tmp44_;
					_tmp39_ = string_to_string (BLUE);
					_tmp40_ = g_strdup_printf ("%u", nbr);
					_tmp41_ = _tmp40_;
					_tmp42_ = string_to_string (NONE);
					_tmp43_ = g_strconcat ("Nombre de coups : ", _tmp39_, _tmp41_, _tmp42_, "\n", NULL);
					_tmp44_ = _tmp43_;
					printf ("%s", _tmp44_);
					_g_free0 (_tmp44_);
					_g_free0 (_tmp41_);
				} else {
					if (nbr < ((guint) 8500)) {
						const gchar* _tmp45_;
						gchar* _tmp46_;
						gchar* _tmp47_;
						const gchar* _tmp48_;
						gchar* _tmp49_;
						gchar* _tmp50_;
						_tmp45_ = string_to_string (YELLOW);
						_tmp46_ = g_strdup_printf ("%u", nbr);
						_tmp47_ = _tmp46_;
						_tmp48_ = string_to_string (NONE);
						_tmp49_ = g_strconcat ("Nombre de coups : ", _tmp45_, _tmp47_, _tmp48_, "\n", NULL);
						_tmp50_ = _tmp49_;
						printf ("%s", _tmp50_);
						_g_free0 (_tmp50_);
						_g_free0 (_tmp47_);
					} else {
						if (nbr < ((guint) 11500)) {
							const gchar* _tmp51_;
							gchar* _tmp52_;
							gchar* _tmp53_;
							const gchar* _tmp54_;
							gchar* _tmp55_;
							gchar* _tmp56_;
							_tmp51_ = string_to_string (ORANGE);
							_tmp52_ = g_strdup_printf ("%u", nbr);
							_tmp53_ = _tmp52_;
							_tmp54_ = string_to_string (NONE);
							_tmp55_ = g_strconcat ("Nombre de coups : ", _tmp51_, _tmp53_, _tmp54_, "\n", NULL);
							_tmp56_ = _tmp55_;
							printf ("%s", _tmp56_);
							_g_free0 (_tmp56_);
							_g_free0 (_tmp53_);
						} else {
							const gchar* _tmp57_;
							gchar* _tmp58_;
							gchar* _tmp59_;
							const gchar* _tmp60_;
							gchar* _tmp61_;
							gchar* _tmp62_;
							_tmp57_ = string_to_string (RED);
							_tmp58_ = g_strdup_printf ("%u", nbr);
							_tmp59_ = _tmp58_;
							_tmp60_ = string_to_string (NONE);
							_tmp61_ = g_strconcat ("Nombre de coups : ", _tmp57_, _tmp59_, _tmp60_, "\n", NULL);
							_tmp62_ = _tmp61_;
							printf ("%s", _tmp62_);
							_g_free0 (_tmp62_);
							_g_free0 (_tmp59_);
						}
					}
				}
			}
		} else {
			gchar* _tmp63_;
			gchar* _tmp64_;
			gchar* _tmp65_;
			gchar* _tmp66_;
			_tmp63_ = g_strdup_printf ("%u", nbr);
			_tmp64_ = _tmp63_;
			_tmp65_ = g_strconcat ("Nombre de coups : \033[1m", _tmp64_, "\033[0m\n", NULL);
			_tmp66_ = _tmp65_;
			printf ("%s", _tmp66_);
			_g_free0 (_tmp66_);
			_g_free0 (_tmp64_);
		}
	}
}

static gchar*
double_to_string (gdouble self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* result = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, (gint) G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}

void
moyenne_run (Moyenne* self)
{
	gint i = 0;
	g_return_if_fail (self != NULL);
	i = 0;
	while (TRUE) {
		gint _tmp0_;
		if (!(i < self->priv->m_foix)) {
			break;
		}
		moyenne_teste (self);
		_tmp0_ = i;
		i = _tmp0_ + 1;
	}
	if (self->priv->m_puissance <= 100) {
		if (self->priv->m_max < ((guint) 700)) {
			const gchar* _tmp1_;
			gchar* _tmp2_;
			gchar* _tmp3_;
			const gchar* _tmp4_;
			gchar* _tmp5_;
			gchar* _tmp6_;
			_tmp1_ = string_to_string (GREEN);
			_tmp2_ = g_strdup_printf ("%u", self->priv->m_max);
			_tmp3_ = _tmp2_;
			_tmp4_ = string_to_string (NONE);
			_tmp5_ = g_strconcat ("max : ", _tmp1_, _tmp3_, _tmp4_, "\n", NULL);
			_tmp6_ = _tmp5_;
			printf ("%s", _tmp6_);
			_g_free0 (_tmp6_);
			_g_free0 (_tmp3_);
		} else {
			if (self->priv->m_max < ((guint) 900)) {
				const gchar* _tmp7_;
				gchar* _tmp8_;
				gchar* _tmp9_;
				const gchar* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
				_tmp7_ = string_to_string (BLUE);
				_tmp8_ = g_strdup_printf ("%u", self->priv->m_max);
				_tmp9_ = _tmp8_;
				_tmp10_ = string_to_string (NONE);
				_tmp11_ = g_strconcat ("max : ", _tmp7_, _tmp9_, _tmp10_, "\n", NULL);
				_tmp12_ = _tmp11_;
				printf ("%s", _tmp12_);
				_g_free0 (_tmp12_);
				_g_free0 (_tmp9_);
			} else {
				if (self->priv->m_max < ((guint) 1100)) {
					const gchar* _tmp13_;
					gchar* _tmp14_;
					gchar* _tmp15_;
					const gchar* _tmp16_;
					gchar* _tmp17_;
					gchar* _tmp18_;
					_tmp13_ = string_to_string (YELLOW);
					_tmp14_ = g_strdup_printf ("%u", self->priv->m_max);
					_tmp15_ = _tmp14_;
					_tmp16_ = string_to_string (NONE);
					_tmp17_ = g_strconcat ("max : ", _tmp13_, _tmp15_, _tmp16_, "\n", NULL);
					_tmp18_ = _tmp17_;
					printf ("%s", _tmp18_);
					_g_free0 (_tmp18_);
					_g_free0 (_tmp15_);
				} else {
					if (self->priv->m_max < ((guint) 1500)) {
						const gchar* _tmp19_;
						gchar* _tmp20_;
						gchar* _tmp21_;
						const gchar* _tmp22_;
						gchar* _tmp23_;
						gchar* _tmp24_;
						_tmp19_ = string_to_string (ORANGE);
						_tmp20_ = g_strdup_printf ("%u", self->priv->m_max);
						_tmp21_ = _tmp20_;
						_tmp22_ = string_to_string (NONE);
						_tmp23_ = g_strconcat ("max : ", _tmp19_, _tmp21_, _tmp22_, "\n", NULL);
						_tmp24_ = _tmp23_;
						printf ("%s", _tmp24_);
						_g_free0 (_tmp24_);
						_g_free0 (_tmp21_);
					} else {
						const gchar* _tmp25_;
						gchar* _tmp26_;
						gchar* _tmp27_;
						const gchar* _tmp28_;
						gchar* _tmp29_;
						gchar* _tmp30_;
						_tmp25_ = string_to_string (RED);
						_tmp26_ = g_strdup_printf ("%u", self->priv->m_max);
						_tmp27_ = _tmp26_;
						_tmp28_ = string_to_string (NONE);
						_tmp29_ = g_strconcat ("max : ", _tmp25_, _tmp27_, _tmp28_, "\n", NULL);
						_tmp30_ = _tmp29_;
						printf ("%s", _tmp30_);
						_g_free0 (_tmp30_);
						_g_free0 (_tmp27_);
					}
				}
			}
		}
	} else {
		if (self->priv->m_puissance <= 500) {
			if (self->priv->m_max < ((guint) 5500)) {
				const gchar* _tmp31_;
				gchar* _tmp32_;
				gchar* _tmp33_;
				const gchar* _tmp34_;
				gchar* _tmp35_;
				gchar* _tmp36_;
				_tmp31_ = string_to_string (GREEN);
				_tmp32_ = g_strdup_printf ("%u", self->priv->m_max);
				_tmp33_ = _tmp32_;
				_tmp34_ = string_to_string (NONE);
				_tmp35_ = g_strconcat ("max : ", _tmp31_, _tmp33_, _tmp34_, "\n", NULL);
				_tmp36_ = _tmp35_;
				printf ("%s", _tmp36_);
				_g_free0 (_tmp36_);
				_g_free0 (_tmp33_);
			} else {
				if (self->priv->m_max < ((guint) 7000)) {
					const gchar* _tmp37_;
					gchar* _tmp38_;
					gchar* _tmp39_;
					const gchar* _tmp40_;
					gchar* _tmp41_;
					gchar* _tmp42_;
					_tmp37_ = string_to_string (BLUE);
					_tmp38_ = g_strdup_printf ("%u", self->priv->m_max);
					_tmp39_ = _tmp38_;
					_tmp40_ = string_to_string (NONE);
					_tmp41_ = g_strconcat ("max : ", _tmp37_, _tmp39_, _tmp40_, "\n", NULL);
					_tmp42_ = _tmp41_;
					printf ("%s", _tmp42_);
					_g_free0 (_tmp42_);
					_g_free0 (_tmp39_);
				} else {
					if (self->priv->m_max < ((guint) 8500)) {
						const gchar* _tmp43_;
						gchar* _tmp44_;
						gchar* _tmp45_;
						const gchar* _tmp46_;
						gchar* _tmp47_;
						gchar* _tmp48_;
						_tmp43_ = string_to_string (YELLOW);
						_tmp44_ = g_strdup_printf ("%u", self->priv->m_max);
						_tmp45_ = _tmp44_;
						_tmp46_ = string_to_string (NONE);
						_tmp47_ = g_strconcat ("max : ", _tmp43_, _tmp45_, _tmp46_, "\n", NULL);
						_tmp48_ = _tmp47_;
						printf ("%s", _tmp48_);
						_g_free0 (_tmp48_);
						_g_free0 (_tmp45_);
					} else {
						if (self->priv->m_max < ((guint) 11500)) {
							const gchar* _tmp49_;
							gchar* _tmp50_;
							gchar* _tmp51_;
							const gchar* _tmp52_;
							gchar* _tmp53_;
							gchar* _tmp54_;
							_tmp49_ = string_to_string (ORANGE);
							_tmp50_ = g_strdup_printf ("%u", self->priv->m_max);
							_tmp51_ = _tmp50_;
							_tmp52_ = string_to_string (NONE);
							_tmp53_ = g_strconcat ("max : ", _tmp49_, _tmp51_, _tmp52_, "\n", NULL);
							_tmp54_ = _tmp53_;
							printf ("%s", _tmp54_);
							_g_free0 (_tmp54_);
							_g_free0 (_tmp51_);
						} else {
							const gchar* _tmp55_;
							gchar* _tmp56_;
							gchar* _tmp57_;
							const gchar* _tmp58_;
							gchar* _tmp59_;
							gchar* _tmp60_;
							_tmp55_ = string_to_string (RED);
							_tmp56_ = g_strdup_printf ("%u", self->priv->m_max);
							_tmp57_ = _tmp56_;
							_tmp58_ = string_to_string (NONE);
							_tmp59_ = g_strconcat ("max : ", _tmp55_, _tmp57_, _tmp58_, "\n", NULL);
							_tmp60_ = _tmp59_;
							printf ("%s", _tmp60_);
							_g_free0 (_tmp60_);
							_g_free0 (_tmp57_);
						}
					}
				}
			}
		} else {
			const gchar* _tmp61_;
			gchar* _tmp62_;
			gchar* _tmp63_;
			const gchar* _tmp64_;
			gchar* _tmp65_;
			gchar* _tmp66_;
			_tmp61_ = string_to_string (GREEN);
			_tmp62_ = g_strdup_printf ("%u", self->priv->m_max);
			_tmp63_ = _tmp62_;
			_tmp64_ = string_to_string (NONE);
			_tmp65_ = g_strconcat ("max:\t\t", _tmp61_, _tmp63_, _tmp64_, "\n", NULL);
			_tmp66_ = _tmp65_;
			printf ("%s", _tmp66_);
			_g_free0 (_tmp66_);
			_g_free0 (_tmp63_);
		}
	}
	self->priv->m_moy = self->priv->m_moy / i;
	if (self->priv->m_puissance <= 100) {
		if (self->priv->m_moy < ((gdouble) 700)) {
			const gchar* _tmp67_;
			gchar* _tmp68_;
			gchar* _tmp69_;
			const gchar* _tmp70_;
			gchar* _tmp71_;
			gchar* _tmp72_;
			_tmp67_ = string_to_string (GREEN);
			_tmp68_ = double_to_string (self->priv->m_moy);
			_tmp69_ = _tmp68_;
			_tmp70_ = string_to_string (NONE);
			_tmp71_ = g_strconcat ("moyenne : ", _tmp67_, _tmp69_, _tmp70_, "\n", NULL);
			_tmp72_ = _tmp71_;
			printf ("%s", _tmp72_);
			_g_free0 (_tmp72_);
			_g_free0 (_tmp69_);
		} else {
			if (self->priv->m_moy < ((gdouble) 900)) {
				const gchar* _tmp73_;
				gchar* _tmp74_;
				gchar* _tmp75_;
				const gchar* _tmp76_;
				gchar* _tmp77_;
				gchar* _tmp78_;
				_tmp73_ = string_to_string (BLUE);
				_tmp74_ = double_to_string (self->priv->m_moy);
				_tmp75_ = _tmp74_;
				_tmp76_ = string_to_string (NONE);
				_tmp77_ = g_strconcat ("moyenne : ", _tmp73_, _tmp75_, _tmp76_, "\n", NULL);
				_tmp78_ = _tmp77_;
				printf ("%s", _tmp78_);
				_g_free0 (_tmp78_);
				_g_free0 (_tmp75_);
			} else {
				if (self->priv->m_moy < ((gdouble) 1100)) {
					const gchar* _tmp79_;
					gchar* _tmp80_;
					gchar* _tmp81_;
					const gchar* _tmp82_;
					gchar* _tmp83_;
					gchar* _tmp84_;
					_tmp79_ = string_to_string (YELLOW);
					_tmp80_ = double_to_string (self->priv->m_moy);
					_tmp81_ = _tmp80_;
					_tmp82_ = string_to_string (NONE);
					_tmp83_ = g_strconcat ("moyenne : ", _tmp79_, _tmp81_, _tmp82_, "\n", NULL);
					_tmp84_ = _tmp83_;
					printf ("%s", _tmp84_);
					_g_free0 (_tmp84_);
					_g_free0 (_tmp81_);
				} else {
					if (self->priv->m_moy < ((gdouble) 1500)) {
						const gchar* _tmp85_;
						gchar* _tmp86_;
						gchar* _tmp87_;
						const gchar* _tmp88_;
						gchar* _tmp89_;
						gchar* _tmp90_;
						_tmp85_ = string_to_string (ORANGE);
						_tmp86_ = double_to_string (self->priv->m_moy);
						_tmp87_ = _tmp86_;
						_tmp88_ = string_to_string (NONE);
						_tmp89_ = g_strconcat ("moyenne : ", _tmp85_, _tmp87_, _tmp88_, "\n", NULL);
						_tmp90_ = _tmp89_;
						printf ("%s", _tmp90_);
						_g_free0 (_tmp90_);
						_g_free0 (_tmp87_);
					} else {
						const gchar* _tmp91_;
						gchar* _tmp92_;
						gchar* _tmp93_;
						const gchar* _tmp94_;
						gchar* _tmp95_;
						gchar* _tmp96_;
						_tmp91_ = string_to_string (RED);
						_tmp92_ = double_to_string (self->priv->m_moy);
						_tmp93_ = _tmp92_;
						_tmp94_ = string_to_string (NONE);
						_tmp95_ = g_strconcat ("moyenne : ", _tmp91_, _tmp93_, _tmp94_, "\n", NULL);
						_tmp96_ = _tmp95_;
						printf ("%s", _tmp96_);
						_g_free0 (_tmp96_);
						_g_free0 (_tmp93_);
					}
				}
			}
		}
	} else {
		if (self->priv->m_puissance <= 500) {
			if (self->priv->m_moy < ((gdouble) 5500)) {
				const gchar* _tmp97_;
				gchar* _tmp98_;
				gchar* _tmp99_;
				const gchar* _tmp100_;
				gchar* _tmp101_;
				gchar* _tmp102_;
				_tmp97_ = string_to_string (GREEN);
				_tmp98_ = double_to_string (self->priv->m_moy);
				_tmp99_ = _tmp98_;
				_tmp100_ = string_to_string (NONE);
				_tmp101_ = g_strconcat ("moyenne : ", _tmp97_, _tmp99_, _tmp100_, "\n", NULL);
				_tmp102_ = _tmp101_;
				printf ("%s", _tmp102_);
				_g_free0 (_tmp102_);
				_g_free0 (_tmp99_);
			} else {
				if (self->priv->m_moy < ((gdouble) 7000)) {
					const gchar* _tmp103_;
					gchar* _tmp104_;
					gchar* _tmp105_;
					const gchar* _tmp106_;
					gchar* _tmp107_;
					gchar* _tmp108_;
					_tmp103_ = string_to_string (BLUE);
					_tmp104_ = double_to_string (self->priv->m_moy);
					_tmp105_ = _tmp104_;
					_tmp106_ = string_to_string (NONE);
					_tmp107_ = g_strconcat ("moyenne : ", _tmp103_, _tmp105_, _tmp106_, "\n", NULL);
					_tmp108_ = _tmp107_;
					printf ("%s", _tmp108_);
					_g_free0 (_tmp108_);
					_g_free0 (_tmp105_);
				} else {
					if (self->priv->m_moy < ((gdouble) 8500)) {
						const gchar* _tmp109_;
						gchar* _tmp110_;
						gchar* _tmp111_;
						const gchar* _tmp112_;
						gchar* _tmp113_;
						gchar* _tmp114_;
						_tmp109_ = string_to_string (YELLOW);
						_tmp110_ = double_to_string (self->priv->m_moy);
						_tmp111_ = _tmp110_;
						_tmp112_ = string_to_string (NONE);
						_tmp113_ = g_strconcat ("moyenne : ", _tmp109_, _tmp111_, _tmp112_, "\n", NULL);
						_tmp114_ = _tmp113_;
						printf ("%s", _tmp114_);
						_g_free0 (_tmp114_);
						_g_free0 (_tmp111_);
					} else {
						if (self->priv->m_moy < ((gdouble) 11500)) {
							const gchar* _tmp115_;
							gchar* _tmp116_;
							gchar* _tmp117_;
							const gchar* _tmp118_;
							gchar* _tmp119_;
							gchar* _tmp120_;
							_tmp115_ = string_to_string (ORANGE);
							_tmp116_ = double_to_string (self->priv->m_moy);
							_tmp117_ = _tmp116_;
							_tmp118_ = string_to_string (NONE);
							_tmp119_ = g_strconcat ("moyenne : ", _tmp115_, _tmp117_, _tmp118_, "\n", NULL);
							_tmp120_ = _tmp119_;
							printf ("%s", _tmp120_);
							_g_free0 (_tmp120_);
							_g_free0 (_tmp117_);
						} else {
							const gchar* _tmp121_;
							gchar* _tmp122_;
							gchar* _tmp123_;
							const gchar* _tmp124_;
							gchar* _tmp125_;
							gchar* _tmp126_;
							_tmp121_ = string_to_string (RED);
							_tmp122_ = double_to_string (self->priv->m_moy);
							_tmp123_ = _tmp122_;
							_tmp124_ = string_to_string (NONE);
							_tmp125_ = g_strconcat ("moyenne : ", _tmp121_, _tmp123_, _tmp124_, "\n", NULL);
							_tmp126_ = _tmp125_;
							printf ("%s", _tmp126_);
							_g_free0 (_tmp126_);
							_g_free0 (_tmp123_);
						}
					}
				}
			}
		} else {
			const gchar* _tmp127_;
			gchar* _tmp128_;
			gchar* _tmp129_;
			const gchar* _tmp130_;
			gchar* _tmp131_;
			gchar* _tmp132_;
			_tmp127_ = string_to_string (GREEN);
			_tmp128_ = double_to_string (self->priv->m_moy);
			_tmp129_ = _tmp128_;
			_tmp130_ = string_to_string (NONE);
			_tmp131_ = g_strconcat ("moyenne:\t\tt", _tmp127_, _tmp129_, _tmp130_, "\n", NULL);
			_tmp132_ = _tmp131_;
			printf ("%s", _tmp132_);
			_g_free0 (_tmp132_);
			_g_free0 (_tmp129_);
		}
	}
}

void
moyenne_teste (Moyenne* self)
{
	gint* tab = NULL;
	gint _tmp0_ = 0;
	gint* _tmp1_;
	gint tab_length1;
	gint _tab_size_;
	gchar* str_tab = NULL;
	gchar* _tmp2_;
	gchar* out_push = NULL;
	gchar* _tmp3_;
	gchar* out_check = NULL;
	gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp1_ = ft_get_random_tab (self->priv->m_puissance, &_tmp0_);
	tab = _tmp1_;
	tab_length1 = _tmp0_;
	_tab_size_ = tab_length1;
	_tmp2_ = ft_tab_to_string (tab, (gint) tab_length1);
	str_tab = _tmp2_;
	_tmp3_ = moyenne_get_push_swap_string (self, str_tab);
	out_push = _tmp3_;
	_tmp4_ = moyenne_call_checker (self, out_push, str_tab);
	out_check = _tmp4_;
	moyenne_print_func (self, out_push, out_check, str_tab);
	_g_free0 (out_check);
	_g_free0 (out_push);
	_g_free0 (str_tab);
	tab = (g_free (tab), NULL);
}

void
moyenne_change_max (Moyenne* self,
                    guint max)
{
	g_return_if_fail (self != NULL);
	if (max > self->priv->m_max) {
		self->priv->m_max = max;
	}
}

void
moyenne_add_moy (Moyenne* self,
                 guint nbr)
{
	g_return_if_fail (self != NULL);
	self->priv->m_moy = self->priv->m_moy + nbr;
}

static void
value_moyenne_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_moyenne_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		moyenne_unref (value->data[0].v_pointer);
	}
}

static void
value_moyenne_copy_value (const GValue* src_value,
                          GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = moyenne_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_moyenne_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_moyenne_collect_value (GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Moyenne * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = moyenne_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_moyenne_lcopy_value (const GValue* value,
                           guint n_collect_values,
                           GTypeCValue* collect_values,
                           guint collect_flags)
{
	Moyenne ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = moyenne_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_moyenne (const gchar* name,
                    const gchar* nick,
                    const gchar* blurb,
                    GType object_type,
                    GParamFlags flags)
{
	ParamSpecMoyenne* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_MOYENNE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_moyenne (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MOYENNE), NULL);
	return value->data[0].v_pointer;
}

void
value_set_moyenne (GValue* value,
                   gpointer v_object)
{
	Moyenne * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MOYENNE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MOYENNE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		moyenne_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		moyenne_unref (old);
	}
}

void
value_take_moyenne (GValue* value,
                    gpointer v_object)
{
	Moyenne * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MOYENNE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MOYENNE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		moyenne_unref (old);
	}
}

static void
moyenne_class_init (MoyenneClass * klass,
                    gpointer klass_data)
{
	moyenne_parent_class = g_type_class_peek_parent (klass);
	((MoyenneClass *) klass)->finalize = moyenne_finalize;
	g_type_class_adjust_private_offset (klass, &Moyenne_private_offset);
}

static void
moyenne_instance_init (Moyenne * self,
                       gpointer klass)
{
	self->priv = moyenne_get_instance_private (self);
	self->ref_count = 1;
}

static void
moyenne_finalize (Moyenne * obj)
{
	Moyenne * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MOYENNE, Moyenne);
	g_signal_handlers_destroy (self);
}

static GType
moyenne_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_moyenne_init, value_moyenne_free_value, value_moyenne_copy_value, value_moyenne_peek_pointer, "p", value_moyenne_collect_value, "p", value_moyenne_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (MoyenneClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) moyenne_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Moyenne), 0, (GInstanceInitFunc) moyenne_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType moyenne_type_id;
	moyenne_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Moyenne", &g_define_type_info, &g_define_type_fundamental_info, 0);
	Moyenne_private_offset = g_type_add_instance_private (moyenne_type_id, sizeof (MoyennePrivate));
	return moyenne_type_id;
}

GType
moyenne_get_type (void)
{
	static volatile gsize moyenne_type_id__volatile = 0;
	if (g_once_init_enter (&moyenne_type_id__volatile)) {
		GType moyenne_type_id;
		moyenne_type_id = moyenne_get_type_once ();
		g_once_init_leave (&moyenne_type_id__volatile, moyenne_type_id);
	}
	return moyenne_type_id__volatile;
}

gpointer
moyenne_ref (gpointer instance)
{
	Moyenne * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
moyenne_unref (gpointer instance)
{
	Moyenne * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MOYENNE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

void
calc_moy (gchar** args,
          gint args_length1)
{
	gint _tmp0_ = 0;
	const gchar* _tmp1_;
	gint puissance = 0;
	gint _tmp3_ = 0;
	gint foix = 0;
	Moyenne* moyenne = NULL;
	Moyenne* _tmp5_;
	_tmp1_ = args[1];
	if (_tmp1_ != NULL) {
		const gchar* _tmp2_;
		_tmp2_ = args[1];
		_tmp0_ = atoi (_tmp2_);
	} else {
		_tmp0_ = 10;
	}
	puissance = _tmp0_;
	if (args_length1 > 2) {
		const gchar* _tmp4_;
		_tmp4_ = args[2];
		_tmp3_ = atoi (_tmp4_);
	} else {
		_tmp3_ = 10;
	}
	foix = _tmp3_;
	_tmp5_ = moyenne_new (puissance, foix);
	moyenne = _tmp5_;
	moyenne_run (moyenne);
	_moyenne_unref0 (moyenne);
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

